version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./sessions:/usr/src/app/sessions
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - APP_PASSWORD=#race4fun 