services:
  - type: web
    name: server-health-monitor
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_PASSWORD
        # This is a placeholder - set a real password in Render dashboard
        value: "#race4fun"
        # For real production use, use a secret
        # sync: false 